name: 💡 Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea clearly so we can understand and evaluate it.

  - type: dropdown
    id: repository
    attributes:
      label: Which repository?
      description: Which Bio-MCP repository would this feature affect?
      options:
        - bio-mcp-blast
        - bio-mcp-samtools
        - bio-mcp-bwa
        - bio-mcp-seqkit
        - bio-mcp-queue
        - bio-mcp-template
        - New repository needed
        - Multiple repositories
      default: 0
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New tool function
        - Performance improvement
        - User interface enhancement
        - Documentation improvement
        - Integration feature
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or features you've considered
      placeholder: "I've also considered..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High - Critical for my workflow
        - Medium - Would be very helpful
        - Low - Nice to have
      default: 1
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I can help with implementation
        - label: I can help with testing
        - label: I can help with documentation
        - label: I would like someone else to implement this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information that might be helpful...